// get to do all
export const GET_TODO_REQUESTED = 'GET_TODO_REQUESTED';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAILED = 'GET_TODO_FAILED';
//add to do
export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';
//remove to do
export const REMOVE_TODO_REQUESTED = 'REMOVE_TODO_REQUESTED';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAILED = 'REMOVE_TODO_FAILED';
// Update to do
export const UPDATE_TODO_REQUESTED = 'UPDATE_TODO_REQUESTED';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED';

//  
export const DELETE_ALL_TODO_REQUESTED = 'DELETE_ALL_TODO_REQUESTED';
export const DELETE_ALL_TODO_SUCCESS = 'DELETE_ALL_TODO_SUCCESS';
// loading
export const SET_LOADING_ID = 'SET_LOADING_ID';
